/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Easy Exam Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2022-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Profile": "Profile",
          "Session expired!": "Session expired!",
          "Please wait": "Please wait",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon":
              "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Updated": "Updated",
          "Something went wrong": "Something went wrong",
          "Timeout": "Timeout",
          "Please select answer": "Please select answer",
          "Getting Results": "Getting Results",
          "Your account is suspended": "Your account is suspended",
          "Something went wrong while login":
              "Something went wrong while login",
          "Something went wrong while signup":
              "Something went wrong while signup",
          "Verification": "Verification",
          "We have sent verification code on":
              "We have sent verification code on",
          "Verify": "Verify",
          "Password mismatch": "Password mismatch",
          "Password Updated": "Password Updated",
          "Edit Profile": "Edit Profile",
          "Change Password": "Change Password",
          "Contact us": "Contact us",
          "Languages": "Languages",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "FAQs": "FAQs",
          "Help": "Help",
          "About Us": "About Us",
          "Terms & Conditions": "Terms & Conditions",
          "Logout": "Logout",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Submit": "Submit",
          "Update Profile": "Update Profile",
          "Choose From": "Choose From",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Cancel": "Cancel",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Start typing to search": "Start typing to search",
          "Search": "Search",
          "Phone Number": "Phone Number",
          "Enrollment Number": "Enrollment Number",
          "Select Studies": "Select Studies",
          "Select Terms": "Select Terms",
          "Update": "Update",
          "Connection Failed": "Connection Failed",
          "Could not connect to network,": "Could not connect to network,",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Exam Name : ": "Exam Name : ",
          "Exam Date : ": "Exam Date : ",
          "Total Marks : ": "Total Marks : ",
          "Passing Marks : ": "Passing Marks : ",
          "Negative Marks : ": "Negative Marks : ",
          "Examiner Name : ": "Examiner Name : ",
          "Your Exam Result : ": "Your Exam Result : ",
          "Passed": "Passed",
          "Failed": "Failed",
          "Your Marks : ": "Your Marks : ",
          "Start Exam": "Start Exam",
          "View Stats": "View Stats",
          "Are you sure": "Are you sure",
          "to quite this exam? your result will count from current exam":
              "to quite this exam? your result will count from current exam",
          "Yes, Quite": "Yes, Quite",
          "Follow Image Question": "Follow Image Question",
          "Get Result": "Get Result",
          "Next Question": "Next Question",
          "Your Exam Stats": "Your Exam Stats",
          "Subjects": "Subjects",
          "Ans.": "Ans.",
          "Learning Name : ": "Learning Name : ",
          "Total Questions : ": "Total Questions : ",
          "Creator Name : ": "Creator Name : ",
          "Login to continue": "Login to continue",
          "Email": "Email",
          "Password": "Password",
          "Login": "Login",
          "Forgot Password?": "Forgot Password?",
          "Don't have an account?": "Don't have an account?",
          "Register": "Register",
          "Let's get started": "Let's get started",
          "Please provide valid details": "Please provide valid details",
          "Already have an account?": "Already have an account?",
          "Reset Password": "Reset Password",
          "Please enter your credentials": "Please enter your credentials",
          "Send OTP": "Send OTP",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Update Password": "Update Password",
          "Congratulations": "Congratulations",
          "Sorry you are failed": "Sorry you are failed",
          "You have passed, in this exam": "You have passed, in this exam",
          "Sorry you are failed, in this exam":
              "Sorry you are failed, in this exam",
          "Here is your marks": "Here is your marks",
          "Go Home": "Go Home",
          "No Internet Connection": "No Internet Connection",
          "Home": "Home",
          "Study": "Study",
          "Account": "Account",
          "No Data Found": "No Data Found",
          "Student Name : ": "Student Name : ",
          "Enrollment : ": "Enrollment : ",
          "Gained Marks : ": "Gained Marks : "
        },
        "hi_IN": {
          "Profile": "प्रोफ़ाइल",
          "Session expired!": "सत्र समाप्त हुआ!",
          "Please wait": "कृपया प्रतीक्षा करें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon":
              "हमें आपका अनुरोध प्राप्त हुआ है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Okay": "ठीक",
          "Updated": "अपडेटेड",
          "Something went wrong": "कुछ गलत हो गया",
          "Timeout": "समय समाप्त",
          "Please select answer": "कृपया उत्तर चुनें",
          "Getting Results": "परिणाम प्राप्त करना",
          "Your account is suspended": "तुम्हारा खाता निलंबित है",
          "Something went wrong while login": "लॉगिन करते समय कुछ गलत हुआ",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड इस पर भेजा है",
          "Verify": "सत्यापित करना",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Change Password": "पासवर्ड बदलें",
          "Contact us": "संपर्क करें",
          "Languages": "भाषाएं",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "FAQs": "अक्सर पूछे जाने वाले प्रश्न",
          "Help": "मदद करना",
          "About Us": "हमारे बारे में",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Logout": "लॉग आउट",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Submit": "प्रस्तुत करना",
          "Update Profile": "प्रोफ़ाइल को नवीनतम बनाओ",
          "Choose From": "से चुनें",
          "Gallery": "गेलरी",
          "Camera": "कैमरा",
          "Cancel": "रद्द करना",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Start typing to search": "खोज के लिए टाइप करना प्रारंभ करें",
          "Search": "खोज",
          "Phone Number": "फ़ोन नंबर",
          "Enrollment Number": "नामांकन संख्या",
          "Select Studies": "अध्ययन का चयन करें",
          "Select Terms": "शर्तें चुनें",
          "Update": "अद्यतन",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network,": "नेटवर्क से कनेक्ट नहीं हो सका,",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Exam Name : ": "परीक्षा का नाम",
          "Exam Date : ": "परीक्षा तिथि",
          "Total Marks : ": "कुल मार्क",
          "Passing Marks : ": "पासिंग मार्क्स",
          "Negative Marks : ": "नकारात्मक अंक",
          "Examiner Name : ": "परीक्षक का नाम",
          "Your Exam Result : ": "आपका परीक्षा परिणाम",
          "Passed": "उत्तीर्ण",
          "Failed": "असफल",
          "Your Marks : ": "आपके अंक",
          "Start Exam": "परीक्षा प्रारंभ करें",
          "View Stats": "आंकड़े देखें",
          "Are you sure": "क्या आपको यकीन है",
          "to quite this exam? your result will count from current exam":
              "इस परीक्षा के लिए? आपका परिणाम वर्तमान परीक्षा से गिना जाएगा",
          "Yes, Quite": "हाँ, काफी",
          "Follow Image Question": "छवि प्रश्न का पालन करें",
          "Get Result": "परिणाम प्राप्त करें",
          "Next Question": "अगला सवाल",
          "Your Exam Stats": "आपके परीक्षा आँकड़े",
          "Subjects": "विषय",
          "Ans.": "उत्तर।",
          "Learning Name : ": "सीखने का नाम",
          "Total Questions : ": "कुल सवाल",
          "Creator Name : ": "निर्माता का नाम",
          "Login to continue": "जारी रखने के लिए लॉगिन करें",
          "Email": "ईमेल",
          "Password": "पासवर्ड",
          "Login": "लॉग इन करें",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Don't have an account?": "क्या आपके पास खाता नहीं है?",
          "Register": "पंजीकरण करवाना",
          "Let's get started": "आएँ शुरू करें",
          "Please provide valid details": "कृपया वैध विवरण प्रदान करें",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          "Reset Password": "पासवर्ड रीसेट",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "Send OTP": "OTP भेजें",
          "New Password": "नया पासवर्ड",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Update Password": "अपडेट पासवर्ड",
          "Congratulations": "बधाई हो",
          "Sorry you are failed": "क्षमा करें, आप असफल रहे",
          "You have passed, in this exam": "आप इस परीक्षा में उत्तीर्ण हुए हैं",
          "Sorry you are failed, in this exam":
              "क्षमा करें, आप इस परीक्षा में असफल रहे",
          "Here is your marks": "यहां आपके निशान हैं",
          "Go Home": "घर जाओ",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Home": "घर",
          "Study": "पढाई करना",
          "Account": "खाता",
          "No Data Found": "कोई डेटा नहीं मिला",
          "Student Name : ": "छात्र का नाम",
          "Enrollment : ": "उपस्थिति पंजी",
          "Gained Marks : ": "प्राप्त अंक"
        },
        "es_DE": {
          "Profile": "Perfil",
          "Session expired!": "Sesión expirada!",
          "Please wait": "Espere por favor",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon":
              "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "Alert!": "Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Updated": "Actualizado",
          "Something went wrong": "Algo salió mal",
          "Timeout": "Se acabó el tiempo",
          "Please select answer": "Por favor seleccione respuesta",
          "Getting Results": "Obtener resultados",
          "Your account is suspended": "Tu cuenta está suspendida",
          "Something went wrong while login":
              "Algo salió mal al iniciar sesión",
          "Something went wrong while signup":
              "Algo salió mal durante el registro",
          "Verification": "Verificación",
          "We have sent verification code on":
              "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza",
          "Edit Profile": "Editar perfil",
          "Change Password": "Cambia la contraseña",
          "Contact us": "Contáctenos",
          "Languages": "Idiomas",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "FAQs": "preguntas frecuentes",
          "Help": "Ayuda",
          "About Us": "Sobre nosotros",
          "Terms & Conditions": "Términos y condiciones",
          "Logout": "Cerrar sesión",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Submit": "Enviar",
          "Update Profile": "Actualización del perfil",
          "Choose From": "Escoge de",
          "Gallery": "Galería",
          "Camera": "Cámara",
          "Cancel": "Cancelar",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Start typing to search": "Empieza a escribir para buscar",
          "Search": "Búsqueda",
          "Phone Number": "Número de teléfono",
          "Enrollment Number": "Numero de inscripcion",
          "Select Studies": "Seleccionar estudios",
          "Select Terms": "Seleccionar términos",
          "Update": "Actualizar",
          "Connection Failed": "La conexión falló",
          "Could not connect to network,": "No se pudo conectar a la red,",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Exam Name : ": "Nombre del examen :",
          "Exam Date : ": "Fecha del examen :",
          "Total Marks : ": "Notas totales :",
          "Passing Marks : ": "Marcas de aprobación :",
          "Negative Marks : ": "marcas negativas :",
          "Examiner Name : ": "Nombre del examinador :",
          "Your Exam Result : ": "El resultado de su examen :",
          "Passed": "Pasó",
          "Failed": "Ha fallado",
          "Your Marks : ": "tus marcas",
          "Start Exam": "Iniciar examen",
          "View Stats": "Ver estadísticas",
          "Are you sure": "Está seguro",
          "to quite this exam? your result will count from current exam":
              "a bastante este examen? su resultado contará desde el examen actual",
          "Yes, Quite": "si bastante",
          "Follow Image Question": "Seguir pregunta de imagen",
          "Get Result": "Obtener resultado",
          "Next Question": "Próxima pregunta",
          "Your Exam Stats": "Las estadísticas de su examen",
          "Subjects": "Asignaturas",
          "Ans.": "Respuesta.",
          "Learning Name : ": "Nombre de aprendizaje :",
          "Total Questions : ": "total de preguntas :",
          "Creator Name : ": "Nombre del creador :",
          "Login to continue": "Iniciar sesión para continuar",
          "Email": "Correo electrónico",
          "Password": "Clave",
          "Login": "Acceso",
          "Forgot Password?": "Has olvidado tu contraseña?",
          "Don't have an account?": "No tienes una cuenta?",
          "Register": "Registro",
          "Let's get started": "Empecemos",
          "Please provide valid details": "Proporcione detalles válidos",
          "Already have an account?": "Ya tienes una cuenta?",
          "Reset Password": "Restablecer la contraseña",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "Send OTP": "Enviar OTP",
          "New Password": "Nueva contraseña",
          "Confirm Password": "Confirmar contraseña",
          "Update Password": "Actualiza contraseña",
          "Congratulations": "Felicidades",
          "Sorry you are failed": "Lo siento, has fallado",
          "You have passed, in this exam": "Has aprobado, en este examen",
          "Sorry you are failed, in this exam":
              "Lo siento, has fallado en este examen.",
          "Here is your marks": "Aquí están tus marcas",
          "Go Home": "Vete a casa",
          "No Internet Connection": "Sin conexión a Internet",
          "Home": "Hogar",
          "Study": "Estudiar",
          "Account": "Cuenta",
          "No Data Found": "Datos no encontrados",
          "Student Name : ": "Nombre del estudiante :",
          "Enrollment : ": "Inscripción :",
          "Gained Marks : ": "Marcas obtenidas :"
        },
        "ar_AE": {
          "Profile": "الملف الشخصي",
          "Session expired!": "انتهت الجلسة!",
          "Please wait": "أرجو الإنتظار",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تلقي طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon":
              "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "معلومات الاتصال المرسلة",
          "Okay": "تمام",
          "Updated": "محدث",
          "Something went wrong": "هناك خطأ ما",
          "Timeout": "نفذ الوقت",
          "Please select answer": "الرجاء تحديد الإجابة",
          "Getting Results": "الحصول على النتائج",
          "Your account is suspended": "تم تعليق حسابك",
          "Something went wrong while login": "حدث خطأ ما أثناء تسجيل الدخول",
          "Something went wrong while signup": "حدث خطأ ما أثناء الاشتراك",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Password Updated": "تم تحديث كلمة السر",
          "Edit Profile": "تعديل الملف الشخصي",
          "Change Password": "غير كلمة السر",
          "Contact us": "اتصل بنا",
          "Languages": "اللغات",
          "Frequently Asked Questions": "أسئلة مكررة",
          "FAQs": "الأسئلة الشائعة",
          "Help": "مساعدة",
          "About Us": "معلومات عنا",
          "Terms & Conditions": "لبنود و الظروف",
          "Logout": "تسجيل خروج",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Submit": "يُقدِّم",
          "Update Profile": "تحديث الملف",
          "Choose From": "اختر من",
          "Gallery": "صالة عرض",
          "Camera": "آلة تصوير",
          "Cancel": "يلغي",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Start typing to search": "ابدأ الكتابة للبحث",
          "Search": "يبحث",
          "Phone Number": "رقم الهاتف",
          "Enrollment Number": "عدد المسجلين",
          "Select Studies": "اختر الدراسات",
          "Select Terms": "حدد الشروط",
          "Update": "تحديث",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network,": "تعذر الاتصال بالشبكة",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "إعادة المحاولة",
          "Exam Name : ": "اسم الامتحان",
          "Exam Date : ": "موعد الامتحان",
          "Total Marks : ": "مجموع علامات",
          "Passing Marks : ": "علامات المرور",
          "Negative Marks : ": "العلامات السلبية",
          "Examiner Name : ": "اسم الممتحن",
          "Your Exam Result : ": "نتيجة اختبارك",
          "Passed": "تم الاجتياز بنجاح",
          "Failed": "باءت بالفشل",
          "Your Marks : ": "علاماتك",
          "Start Exam": "بدء الاختبار",
          "View Stats": "عرض احصائيات",
          "Are you sure": "هل أنت واثق",
          "to quite this exam? your result will count from current exam":
              "إلى هذا الاختبار تمامًا؟ سيتم احتساب نتيجتك من الاختبار الحالي",
          "Yes, Quite": "نعم ، تمامًا",
          "Follow Image Question": "متابعة سؤال الصورة",
          "Get Result": "الحصول على النتيجة",
          "Next Question": "السؤال التالي",
          "Your Exam Stats": "إحصائيات اختبارك",
          "Subjects": "المواضيع",
          "Ans.": "الجواب.",
          "Learning Name : ": "اسم التعلم",
          "Total Questions : ": "مجموع الأسئلة",
          "Creator Name : ": "اسم المنشئ",
          "Login to continue": "تسجيل الدخول للمتابعة",
          "Email": "البريد الإلكتروني",
          "Password": "كلمة المرور",
          "Login": "تسجيل الدخول",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Don't have an account?": "ليس لديك حساب؟",
          "Register": "يسجل",
          "Let's get started": "هيا بنا نبدأ",
          "Please provide valid details": "الرجاء تقديم تفاصيل صحيحة",
          "Already have an account?": "هل لديك حساب؟",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please enter your credentials":
              "الرجاء إدخال بيانات الاعتماد الخاصة بك",
          "Send OTP": "إرسال OTP",
          "New Password": "كلمة السر الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Update Password": "تطوير كلمة السر",
          "Congratulations": "تهانينا",
          "Sorry you are failed": "آسف ، لقد فشلت",
          "You have passed, in this exam": "لقد نجحت ، في هذا الاختبا",
          "Sorry you are failed, in this exam":
              "آسف لأنك فشلت ، في هذا الاختبار",
          "Here is your marks": "هذه هي علاماتك",
          "Go Home": "اذهب للمنزل",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Home": "مسكن",
          "Study": "يذاكر",
          "Account": "الحساب",
          "No Data Found": "لاتوجد بيانات",
          "Student Name : ": "أسم الطالب",
          "Enrollment : ": "التسجيل",
          "Gained Marks : ": "العلامات المكتسبة"
        },
      };
}
